# Generated by Django 5.2.16 on 2026-07-23 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_author_author_death_not_before_birth'),
        ('catalog', '0004_track_review_workflow'),
        ('narrators', '0001_initial'),
        ('playlists', '0002_playlist_playlist_type_owner_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_plays', models.PositiveBigIntegerField(default=0)),
                ('unique_listeners', models.PositiveBigIntegerField(default=0)),
                ('listening_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('completed_plays', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date', 'id'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('date',), name='analytics_unique_platform_date')],
            },
        ),
        migrations.CreateModel(
            name='DailyAuthorMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_plays', models.PositiveBigIntegerField(default=0)),
                ('unique_listeners', models.PositiveBigIntegerField(default=0)),
                ('listening_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('completed_plays', models.PositiveBigIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='authors.author')),
            ],
            options={
                'ordering': ('-date', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['date', '-total_plays'], name='analytics_author_popular_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'author'), name='analytics_unique_author_date')],
            },
        ),
        migrations.CreateModel(
            name='DailyNarratorMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_plays', models.PositiveBigIntegerField(default=0)),
                ('unique_listeners', models.PositiveBigIntegerField(default=0)),
                ('listening_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('completed_plays', models.PositiveBigIntegerField(default=0)),
                ('narrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='narrators.narrator')),
            ],
            options={
                'ordering': ('-date', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['date', '-total_plays'], name='analytics_narrator_pop_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'narrator'), name='analytics_unique_narrator_date')],
            },
        ),
        migrations.CreateModel(
            name='DailyPlaylistMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_plays', models.PositiveBigIntegerField(default=0)),
                ('unique_listeners', models.PositiveBigIntegerField(default=0)),
                ('listening_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('completed_plays', models.PositiveBigIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='playlists.playlist')),
            ],
            options={
                'ordering': ('-date', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['date', '-total_plays'], name='analytics_playlist_pop_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'playlist'), name='analytics_unique_playlist_date')],
            },
        ),
        migrations.CreateModel(
            name='DailyTrackMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_plays', models.PositiveBigIntegerField(default=0)),
                ('unique_listeners', models.PositiveBigIntegerField(default=0)),
                ('listening_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('completed_plays', models.PositiveBigIntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='catalog.audiotrack')),
            ],
            options={
                'ordering': ('-date', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['date', '-total_plays'], name='analytics_track_popular_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'track'), name='analytics_unique_track_date')],
            },
        ),
    ]
