# Generated by Django 5.2.16 on 2026-08-17 10:00

import apps.common.storage
import apps.common.uploads
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0016_audiotrack_spoken_introduction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('audio_file', models.FileField(storage=apps.common.storage.processed_audio_storage, upload_to=apps.common.uploads.processed_audio_upload_path, validators=[apps.common.validators.validate_audio_upload])),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('frequency', models.PositiveSmallIntegerField(default=3, help_text='Minimum main-audio starts between plays of this advertisement.', validators=[django.core.validators.MinValueValidator(2)])),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('-is_enabled', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AudioAdvertisementPlayback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(db_index=True)),
                ('playback_sequence', models.PositiveBigIntegerField()),
                ('source', models.CharField(max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbacks', to='audio_ads.audioadvertisement')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_ad_playbacks', to='catalog.audiotrack')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_ad_playbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['advertisement', '-started_at'], name='audio_ads_ad_started_idx'), models.Index(fields=['session_id', '-playback_sequence'], name='audio_ads_session_seq_idx')],
                'constraints': [models.UniqueConstraint(fields=('advertisement', 'session_id', 'playback_sequence'), name='audio_ads_unique_started_playback')],
            },
        ),
    ]
