# Generated by Django 5.2.16 on 2026-07-23 14:09

import apps.common.uploads
import apps.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('name_ne', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('biography_ne', models.TextField(blank=True)),
                ('biography_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.common.uploads.image_upload_path, validators=[apps.common.validators.validate_image_upload])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('name_ne', 'id'),
                'indexes': [models.Index(fields=['is_featured', 'is_verified', 'name_ne'], name='author_featured_verified_idx')],
            },
        ),
    ]
