# Generated by Django 5.2.16 on 2026-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__isnull', True), ('death_date__isnull', True), ('death_date__gte', models.F('birth_date')), _connector='OR'), name='author_death_not_before_birth'),
        ),
    ]
