# Generated by Django 5.2.16 on 2026-07-23 14:37

import apps.common.uploads
import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_audiotrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('title_ne', models.CharField(max_length=250)),
                ('title_en', models.CharField(blank=True, max_length=250)),
                ('description_ne', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.common.uploads.image_upload_path, validators=[apps.common.validators.validate_image_upload])),
                ('playlist_type', models.CharField(choices=[('editorial', 'Editorial'), ('user', 'User'), ('automatic', 'Automatic')], db_index=True, default='user', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], db_index=True, default='private', max_length=16)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_items_added', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='catalog.audiotrack')),
            ],
            options={
                'ordering': ('position', 'created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='playlists.PlaylistItem', to='catalog.audiotrack'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'position'], name='playlist_item_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(fields=('playlist', 'track'), name='playlist_unique_track'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='playlist_unique_position'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['visibility', 'is_published', '-created_at'], name='playlist_public_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['is_featured', 'visibility', 'is_published'], name='playlist_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner', 'playlist_type', '-updated_at'], name='playlist_owner_type_idx'),
        ),
    ]
