# Generated by Django 5.2.16 on 2026-07-23 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_audiotrack'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('playlist_type', 'user')), models.Q(models.Q(('playlist_type', 'user'), _negated=True), ('owner__isnull', True)), _connector='OR'), name='playlist_type_owner_valid'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.CheckConstraint(condition=models.Q(('is_featured', False), ('playlist_type', 'editorial'), _connector='OR'), name='playlist_featured_editorial_only'),
        ),
    ]
