# Generated by Django 5.2.16 on 2026-09-01 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_audiotrack_track_work_order_idx_and_more'),
        ('playlists', '0004_user_playlists_are_not_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playlistitem',
            name='playlist_unique_track',
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='catalog.literarywork'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='catalog.audiotrack'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('track__isnull', False), ('work__isnull', True)), models.Q(('track__isnull', True), ('work__isnull', False)), _connector='OR'), name='playlist_item_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', False)), fields=('playlist', 'track'), name='playlist_unique_track'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('work__isnull', False)), fields=('playlist', 'work'), name='playlist_unique_work'),
        ),
    ]
