# Generated by Django 5.2.16 on 2026-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_administrative_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeaudit',
            options={'ordering': ('-created_at', '-id'), 'permissions': [('import_metadata', 'Can import controlled metadata'), ('export_metadata', 'Can export controlled metadata')]},
        ),
        migrations.AlterField(
            model_name='administrativeaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Content created'), ('edited', 'Content edited'), ('review_submitted', 'Review submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('processing_retried', 'Audio processing retried'), ('playlist_reordered', 'Playlist reordered'), ('homepage_changed', 'Homepage changed'), ('copyright_verified', 'Copyright verified'), ('copyright_revoked', 'Copyright verification revoked'), ('subscription_changed', 'Subscription changed'), ('user_suspended', 'User suspended'), ('user_reactivated', 'User reactivated'), ('metadata_imported', 'Metadata imported'), ('metadata_exported', 'Metadata exported')], db_index=True, max_length=32),
        ),
    ]
