# Generated by Django 5.2.16 on 2026-07-23 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('followed_author_published', 'Followed author published new content'), ('followed_narrator_published', 'Followed narrator published new content'), ('playlist_updated', 'Playlist updated'), ('upload_processing_completed', 'Upload processing completed'), ('upload_processing_failed', 'Upload processing failed'), ('creator_submission_approved', 'Creator submission approved'), ('creator_submission_rejected', 'Creator submission rejected')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deduplication_key', models.CharField(blank=True, max_length=200)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_recipient_unread_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deduplication_key', ''), _negated=True), fields=('recipient', 'deduplication_key'), name='notification_unique_recipient_dedup')],
            },
        ),
    ]
