# Generated by Django 5.2.16 on 2026-07-23 14:21

import apps.common.uploads
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_author_author_death_not_before_birth'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('title_ne', models.CharField(max_length=250)),
                ('title_en', models.CharField(blank=True, max_length=250)),
                ('description_ne', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.common.uploads.image_upload_path, validators=[apps.common.validators.validate_image_upload])),
                ('album_type', models.CharField(choices=[('collection', 'Collection'), ('anthology', 'Anthology'), ('audiobook', 'Audiobook'), ('series', 'Series')], default='collection', max_length=24)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='authors.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='albums', to='taxonomy.genre')),
                ('moods', models.ManyToManyField(blank=True, related_name='albums', to='taxonomy.mood')),
            ],
            options={
                'ordering': ('-release_date', 'title_ne', 'id'),
                'indexes': [models.Index(fields=['is_published', 'is_featured', '-release_date'], name='album_public_featured_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiteraryWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('title_ne', models.CharField(max_length=250)),
                ('title_en', models.CharField(blank=True, max_length=250)),
                ('subtitle_ne', models.CharField(blank=True, max_length=300)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('description_ne', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('poem', 'Poem'), ('story', 'Story'), ('essay', 'Essay'), ('novel_chapter', 'Novel chapter'), ('folk_tale', 'Folk tale'), ('drama', 'Drama')], max_length=24)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('copyright_status', models.CharField(choices=[('copyrighted', 'Copyrighted'), ('licensed', 'Licensed'), ('permission_granted', 'Permission granted'), ('public_domain', 'Public domain'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('copyright_owner', models.CharField(blank=True, max_length=250)),
                ('license_notes', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.common.uploads.image_upload_path, validators=[apps.common.validators.validate_image_upload])),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='literary_works', to='authors.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='literary_works', to='taxonomy.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='literary_works', to='taxonomy.language')),
                ('moods', models.ManyToManyField(blank=True, related_name='literary_works', to='taxonomy.mood')),
            ],
            options={
                'ordering': ('-published_at', 'title_ne', 'id'),
                'indexes': [models.Index(fields=['is_published', 'is_featured', '-published_at'], name='work_public_featured_idx'), models.Index(fields=['content_type', 'is_published'], name='work_type_published_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_published', False), ('published_at__isnull', False), _connector='OR'), name='work_published_requires_timestamp')],
            },
        ),
    ]
