# Generated by Django 5.2.16 on 2026-07-23 14:28

import apps.common.uploads
import apps.common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('narrators', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('chapter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('track_number', models.PositiveIntegerField(blank=True, null=True)),
                ('title_ne', models.CharField(max_length=250)),
                ('title_en', models.CharField(blank=True, max_length=250)),
                ('description_ne', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('audio_master_file', models.FileField(blank=True, upload_to=apps.common.uploads.audio_upload_path, validators=[apps.common.validators.validate_audio_upload])),
                ('stream_file_high', models.FileField(blank=True, upload_to=apps.common.uploads.audio_upload_path, validators=[apps.common.validators.validate_audio_upload])),
                ('stream_file_low', models.FileField(blank=True, upload_to=apps.common.uploads.audio_upload_path, validators=[apps.common.validators.validate_audio_upload])),
                ('waveform_data', models.JSONField(blank=True, default=list)),
                ('transcript', models.TextField(blank=True)),
                ('is_explicit', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('play_count_cache', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(choices=[('poem', 'Poem'), ('story', 'Story'), ('essay', 'Essay'), ('novel_chapter', 'Novel chapter'), ('folk_tale', 'Folk tale'), ('drama', 'Drama')], db_index=True, editable=False, max_length=24)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_tracks', to='catalog.album')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_tracks', to='taxonomy.language')),
                ('narrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_tracks', to='narrators.narrator')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_tracks', to='catalog.literarywork')),
            ],
            options={
                'ordering': ('album_id', 'track_number', 'chapter_number', 'title_ne', 'id'),
                'indexes': [models.Index(fields=['is_published', 'is_featured', '-published_at'], name='track_public_featured_idx'), models.Index(fields=['content_type', 'is_published', '-published_at'], name='track_type_published_idx'), models.Index(fields=['narrator', 'is_published', '-published_at'], name='track_narrator_public_idx'), models.Index(fields=['work', 'track_number'], name='track_work_order_idx'), models.Index(fields=['album', 'track_number'], name='track_album_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_published', False), models.Q(('published_at__isnull', False), ('processing_status', 'ready')), _connector='OR'), name='track_publish_requires_ready_timestamp')],
            },
        ),
    ]
