# Generated by Django 5.2.16 on 2026-07-27 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_jobs_for_existing_processing_tracks(apps, schema_editor):
    del schema_editor
    AudioTrack = apps.get_model("catalog", "AudioTrack")
    AudioProcessingJob = apps.get_model("catalog", "AudioProcessingJob")
    jobs = []
    for track in AudioTrack.objects.filter(
        processing_status__in=("pending", "processing", "failed")
    ).iterator():
        if track.processing_status == "pending" and not track.audio_master_file:
            continue
        jobs.append(
            AudioProcessingJob(
                track_id=track.pk,
                status=(
                    "queued"
                    if track.processing_status == "pending"
                    else track.processing_status
                ),
                stage="upload",
                error_summary=(
                    "Legacy processing failure; inspect historical worker logs."
                    if track.processing_status == "failed"
                    else ""
                ),
                last_attempt_at=(
                    track.updated_at if track.processing_status == "failed" else None
                ),
            )
        )
    AudioProcessingJob.objects.bulk_create(jobs)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_track_review_workflow'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('stage', models.CharField(choices=[('upload', 'Upload validation'), ('transcoding', 'Audio transcoding'), ('waveform', 'Waveform generation'), ('metadata', 'Metadata extraction'), ('finalizing', 'Finalizing')], db_index=True, default='upload', max_length=24)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('technical_error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='catalog.audiotrack')),
                ('upload_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='uploads.uploadsession')),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
                'indexes': [models.Index(fields=['status', 'stage', '-last_attempt_at'], name='audio_job_status_stage_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_attempts__gt', 0)), name='audio_job_max_attempts_positive'), models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='audio_job_attempts_within_max')],
            },
        ),
        migrations.RunPython(
            create_jobs_for_existing_processing_tracks,
            migrations.RunPython.noop,
        ),
    ]
