# Generated by Django 5.2.16 on 2026-07-29 14:07

import apps.common.storage
import apps.common.uploads
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_staff_action_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiondocument',
            name='document',
            field=models.FileField(storage=apps.common.storage.original_audio_storage, upload_to=apps.common.uploads.permission_document_upload_path, validators=[apps.common.validators.validate_permission_document_upload]),
        ),
    ]
