# Generated by Django 5.2.16 on 2026-09-01 15:56

import apps.common.uploads
import apps.common.validators
from django.conf import settings
from django.db import migrations, models


def populate_categories_and_validate_chapters(apps, schema_editor):
    LiteraryWork = apps.get_model("catalog", "LiteraryWork")
    AudioTrack = apps.get_model("catalog", "AudioTrack")
    through = LiteraryWork.categories.through
    through.objects.bulk_create(
        [
            through(
                literarywork_id=work_id,
                contentcategory_id=category_id,
            )
            for work_id, category_id in LiteraryWork.objects.values_list(
                "id", "category_id"
            )
        ],
        ignore_conflicts=True,
    )

    duplicates = list(
        AudioTrack.objects.exclude(chapter_number__isnull=True)
        .values("work_id", "chapter_number")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)[:10]
    )
    if duplicates:
        raise RuntimeError(
            "Duplicate chapter numbers must be resolved before migration: "
            f"{duplicates}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_author_death_not_before_birth'),
        ('catalog', '0016_audiotrack_spoken_introduction'),
        ('narrators', '0001_initial'),
        ('taxonomy', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='audiotrack',
            name='track_work_order_idx',
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=apps.common.uploads.image_upload_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='literarywork',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Additional browse categories. The primary category is always included.', related_name='categorized_literary_works', to='taxonomy.contentcategory'),
        ),
        migrations.AddField(
            model_name='literarywork',
            name='structure',
            field=models.CharField(choices=[('standalone', 'Standalone'), ('serialized', 'Serialized')], db_index=True, default='standalone', max_length=16),
        ),
        migrations.AddField(
            model_name='literarywork',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='literary_works', to='taxonomy.tag'),
        ),
        migrations.RunPython(
            populate_categories_and_validate_chapters,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['work', 'chapter_number'], name='track_work_order_idx'),
        ),
        migrations.AddIndex(
            model_name='literarywork',
            index=models.Index(fields=['structure', 'is_published', '-published_at'], name='work_structure_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiotrack',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter_number__isnull', False)), fields=('work', 'chapter_number'), name='catalog_unique_work_chapter_number'),
        ),
    ]
