# Generated by Django 5.2.16 on 2026-09-01 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_audiotrack_track_work_order_idx_and_more'),
        ('narrators', '0001_initial'),
        ('taxonomy', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['work', 'track_number'], name='track_work_legacy_order_idx'),
        ),
    ]
