# Generated by Django 5.2.16 on 2026-07-23 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_author_author_death_not_before_birth'),
        ('catalog', '0004_track_review_workflow'),
        ('narrators', '0001_initial'),
        ('playlists', '0002_playlist_playlist_type_owner_valid_and_more'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.SlugField(max_length=120, unique=True)),
                ('title_ne', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('continue_listening', 'Continue listening'), ('tracks', 'Tracks'), ('playlists', 'Playlists'), ('albums', 'Albums'), ('authors', 'Authors'), ('narrators', 'Narrators'), ('genres', 'Genres'), ('moods', 'Moods')], max_length=24)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('sort_order', 'identifier', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='home_section_valid_schedule')],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='catalog.album')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='authors.author')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='taxonomy.genre')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='taxonomy.mood')),
                ('narrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='narrators.narrator')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='playlists.playlist')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.homesection')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='catalog.audiotrack')),
            ],
            options={
                'ordering': ('position', 'created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('section', 'position'), name='home_section_item_unique_position'), models.CheckConstraint(condition=models.Q(models.Q(('track__isnull', False), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True)), models.Q(('playlist__isnull', False), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True), ('track__isnull', True)), models.Q(('album__isnull', False), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True), ('track__isnull', True), ('playlist__isnull', True)), models.Q(('author__isnull', False), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True)), models.Q(('narrator__isnull', False), ('genre__isnull', True), ('mood__isnull', True), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True)), models.Q(('genre__isnull', False), ('mood__isnull', True), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True)), models.Q(('mood__isnull', False), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True)), _connector='OR'), name='home_section_item_exactly_one_target')],
            },
        ),
    ]
