# Generated by Django 5.2.16 on 2026-08-06 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='layout',
            field=models.CharField(choices=[('rail', 'Horizontal rail'), ('grid', 'Responsive grid')], default='rail', max_length=16),
        ),
        migrations.AddField(
            model_name='homesection',
            name='max_items',
            field=models.PositiveSmallIntegerField(default=6, help_text='Maximum number of visible items (1–12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subtitle_ne',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
