# Generated by Django 5.2.16 on 2026-08-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_author_death_not_before_birth'),
        ('catalog', '0015_replace_content_type_with_category'),
        ('home', '0002_homesection_layout_homesection_max_items_and_more'),
        ('narrators', '0001_initial'),
        ('playlists', '0003_playlistitem_position_index'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homesectionitem',
            name='home_section_item_exactly_one_target',
        ),
        migrations.AddField(
            model_name='homesectionitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='taxonomy.contentcategory'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('continue_listening', 'Continue listening'), ('tracks', 'Tracks'), ('playlists', 'Playlists'), ('albums', 'Albums'), ('authors', 'Authors'), ('narrators', 'Narrators'), ('genres', 'Genres'), ('moods', 'Moods'), ('categories', 'Categories')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='homesectionitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('track__isnull', False), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True), ('category__isnull', True)), models.Q(('playlist__isnull', False), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True), ('category__isnull', True), ('track__isnull', True)), models.Q(('album__isnull', False), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True), ('category__isnull', True), ('track__isnull', True), ('playlist__isnull', True)), models.Q(('author__isnull', False), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True), ('category__isnull', True), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True)), models.Q(('narrator__isnull', False), ('genre__isnull', True), ('mood__isnull', True), ('category__isnull', True), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True)), models.Q(('genre__isnull', False), ('mood__isnull', True), ('category__isnull', True), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True)), models.Q(('mood__isnull', False), ('category__isnull', True), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True)), models.Q(('category__isnull', False), ('track__isnull', True), ('playlist__isnull', True), ('album__isnull', True), ('author__isnull', True), ('narrator__isnull', True), ('genre__isnull', True), ('mood__isnull', True)), _connector='OR'), name='home_section_item_exactly_one_target'),
        ),
    ]
