# Generated by Django 5.2.16 on 2026-07-23 14:09

import apps.common.uploads
import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('name_ne', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('biography_ne', models.TextField(blank=True)),
                ('biography_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.common.uploads.image_upload_path, validators=[apps.common.validators.validate_image_upload])),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('follower_count_cache', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_ne', 'id'),
                'indexes': [models.Index(fields=['is_featured', 'is_verified', 'name_ne'], name='narrator_featured_verified_idx'), models.Index(fields=['-follower_count_cache', 'name_ne'], name='narrator_followers_idx')],
            },
        ),
    ]
